spring:
  application:
    name: MainApp
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: always